## Delhi

In [5]:
import requests
import html_to_json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import selenium
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import time
import re
import pandas as pd

In [55]:
homepage = 'https://vegetablemarketprice.com/'
data = []
html_list = []
driver = webdriver.Firefox()
driver.get(homepage)
search_input = driver.find_element(by=By.XPATH, value='//*[@id="header-search-input"]')

header_search_input = 'Delhi Vegetable Market Price History'
search_input.send_keys(header_search_input)
search_input.send_keys(Keys.ENTER)
time.sleep(5)
driver.find_element(by=By.XPATH,value='/html/body/ul/li[1]/div').click()


switch = driver.find_element(By.XPATH, '//*[@id="navItemTable"]')
switch.click()

change_date = driver.find_element(by = By.XPATH,value = '//*[@id="reportrange"]')

change_date.click()
custom_range = driver.find_element(By.XPATH, "//*[contains(text(), 'Custom Range')]")
custom_range.click()

In [56]:
# Initialzing the dates
while True: 
    check_month = driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div[1]/table/thead/tr[1]/th[2]")
    month = check_month.get_attribute("innerHTML")
    if month == "Feb 2022":
        break
        
    else:
        back_button = driver.find_element(By.XPATH,'/html/body/div[4]/div[2]/div[1]/table/thead/tr[1]/th[1]')

        back_button.click()
        
first_date = driver.find_element(By.XPATH, '/html/body/div[4]/div[2]/div[1]/table/tbody/tr[1]/td[3]')
first_date.click()

In [58]:
# selecting date from feb to july
i=0
while i <= 2:
    front_button = driver.find_element(By.XPATH,"/html/body/div[4]/div[3]/div[1]/table/thead/tr[1]/th[3]")
    front_button.click()
    i = i+1

last_date = driver.find_element(By.XPATH,"/html/body/div[4]/div[3]/div[1]/table/tbody/tr[5]/td[7]")
last_date.click()

In [59]:
apply_button = driver.find_element(By.XPATH, '/html/body/div[4]/div[4]/button[2]')
driver.execute_script("arguments[0].scrollIntoView();", apply_button)
apply_button.click()

In [14]:
final_list = ['Onion Big', 'Onion Small', 'Tomato', 'Green Chilli', 'Beetroot', 'Potato',
    'Raw Banana (Plantain)', 'Amaranth Leaves', 'Amla', 'Ash gourd', 'Baby Corn',
    'Banana Flower', 'Capsicum', 'Bitter Gourd', 'Bottle Gourd', 'Butter Beans',
    'Broad Beans', 'Cabbage', 'Carrot', 'Cauliflower', 'Cluster beans', 'Coconut',
    'Colocasia Leaves', 'Colocasia', 'Coriander Leaves', 'Corn', 'Cucumber',
    'Curry Leaves', 'Dill Leaves', 'Drumsticks', 'Brinjal', 'Brinjal (Big)',
    'Elephant Yam', 'Fenugreek Leaves', 'French Beans', 'Garlic', 'Ginger',
    'Onion Green', 'Green Peas', 'Ivy Gourd', 'Lemon (Lime)', 'Mango Raw',
    'Mint Leaves', 'Mushroom', 'Mustard Leaves', 'Ladies Finger', 'Pumpkin',
    'Radish', 'Ridge Gourd', 'Shallot (Pearl Onion)', 'Snake Gourd', 'Sorrel Leaves',
    'Spinach', 'Sweet Potato']

In [61]:
for i in range (0,len(final_list)):
    while True:
        try:
            element = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div/div[1]/button')
            element.click()
        except:
            break
    search_input = driver.find_element(By.NAME, 'search_terms')
    search_input.send_keys(final_list[i])
    time.sleep(3)
    search_input.send_keys(Keys.ENTER)
    
    temp = driver.find_element(By.XPATH, '//*[@id="historyDataTable"]')
    time.sleep(3)
    temp_html = temp.get_attribute("innerHTML")
    html_list.append(temp_html)
    time.sleep(3)
    print(final_list[i])

Onion Big
Onion Small
Tomato
Green Chilli
Beetroot
Potato
Raw Banana (Plantain)
Amaranth Leaves
Amla
Ash gourd
Baby Corn
Banana Flower
Capsicum
Bitter Gourd
Bottle Gourd
Butter Beans
Broad Beans
Cabbage
Carrot
Cauliflower
Cluster beans
Coconut
Colocasia Leaves
Colocasia
Coriander Leaves
Corn
Cucumber
Curry Leaves
Dill Leaves
Drumsticks
Brinjal
Brinjal (Big)
Elephant Yam
Fenugreek Leaves
French Beans
Garlic
Ginger
Onion Green
Green Peas
Ivy Gourd
Lemon (Lime)
Mango Raw
Mint Leaves
Mushroom
Mustard Leaves
Ladies Finger
Pumpkin
Radish
Ridge Gourd
Shallot (Pearl Onion)
Snake Gourd
Sorrel Leaves
Spinach
Sweet Potato

In [62]:
date = re.findall('<th>(.*?)</th>',html_list[0])
dates = []
for i in date:
    temp = re.findall('"white-space: nowrap;">(.*?)</span>',i)
    if len(temp) != 0:
        dates.append(temp)

In [63]:
Name = []
Prices = []

for i in html_list:
    temp_n = re.findall('<tbody><tr><td>(.*?)</td><td>',i)
    Name.extend(temp_n)
    
    temp_p = re.findall('<td>â‚¹ (.*?)</td>',i)
    Prices.append(temp_p)

In [64]:
#converting into dataframe 
df = pd.DataFrame(dates,columns = ['Dates'])
df1 = pd.DataFrame(Prices)
df1 = df1.transpose()
df1.dropna(inplace = True)
df1.columns = [Name]
df = pd.merge(df,df1,left_index=True, right_index=True)

In [65]:
df

,Dates,"(Onion Big,)","(Onion Small,)","(Tomato,)","(Green Chilli,)","(Beetroot,)","(Potato,)","(Raw Banana (Plantain),)","(Amaranth Leaves,)","(Amla,)",...,"(Mustard Leaves,)","(Ladies Finger,)","(Pumpkin,)","(Radish,)","(Ridge Gourd,)","(Shallot (Pearl Onion),)","(Snake Gourd,)","(Sorrel Leaves,)","(Spinach,)","(Sweet Potato,)"
0,2022-02-01,36,62,19,42,49,22,5,15,60,...,20,59,26,24,30,34,25,13,12,38
1,2022-02-02,39,63,17,36,50,21,4,17,60,...,15,57,24,24,30,36,25,11,15,43
2,2022-02-03,39,63,17,36,50,21,4,17,60,...,15,57,24,24,30,36,25,11,15,43
3,2022-02-04,39,63,17,36,50,21,4,17,60,...,15,57,24,24,30,36,25,11,15,43
4,2022-02-05,38,63,21,45,48,26,4,12,60,...,17,58,21,21,33,31,28,13,10,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2022-07-26,25,34,17,33,45,29,7,10,60,...,12,33,20,24,30,37,29,13,12,37
176,2022-07-27,25,34,17,33,45,29,7,10,60,...,12,33,20,24,30,37,29,13,12,37
177,2022-07-28,25,34,17,33,45,29,7,10,60,...,12,33,20,24,30,37,29,13,12,37
178,2022-07-29,25,34,17,33,45,29,7,10,60,...,12,33,20,24,30,37,29,13,12,37
179,2022-07-30,25,34,17,33,45,29,7,10,60,...,12,33,20,24,30,37,29,13,12,37

In [66]:
# exporting the data into csv file
path = 'C:\\Users\\91982\\Downloads\\project\\FEB_JULY_Prices_Delhi.csv'
df.to_csv(path, index=False)

## Extracting data from aug to dec

In [48]:
#visiting to noida market price history from main page
homepage = 'https://vegetablemarketprice.com/'
data = []
html_list = []
driver = webdriver.Firefox()
driver.get(homepage)
search_input = driver.find_element(by=By.XPATH, value='//*[@id="header-search-input"]')

header_search_input = 'Delhi Vegetable Market Price History'
search_input.send_keys(header_search_input)
search_input.send_keys(Keys.ENTER)
time.sleep(5)
driver.find_element(by=By.XPATH,value='/html/body/ul/li[1]/div').click()

#selecting table in dashboard
switch = driver.find_element(By.XPATH, '//*[@id="navItemTable"]')
switch.click()

#selecting custom range from the date 
change_date = driver.find_element(by = By.XPATH,value = '//*[@id="reportrange"]')
change_date.click()
custom_range = driver.find_element(By.XPATH, "//*[contains(text(), 'Custom Range')]")
custom_range.click()


# Initialzing the dates
while True: 
    check_month = driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div[1]/table/thead/tr[1]/th[2]")
    month = check_month.get_attribute("innerHTML")
    if month == "Aug 2022":
        break
        
    else:
        back_button = driver.find_element(By.XPATH,'/html/body/div[4]/div[2]/div[1]/table/thead/tr[1]/th[1]')

        back_button.click()
        
first_date = driver.find_element(By.XPATH, '/html/body/div[4]/div[2]/div[1]/table/tbody/tr[1]/td[2]')
first_date.click()

#selecting date from Aug to Dec
i=0
while i <= 2:
    front_button = driver.find_element(By.XPATH,"/html/body/div[4]/div[3]/div[1]/table/thead/tr[1]/th[3]")
    front_button.click()
    i = i+1

last_date = driver.find_element(By.XPATH,"/html/body/div[4]/div[3]/div[1]/table/tbody/tr[5]/td[7]")
last_date.click()

apply_button = driver.find_element(By.XPATH,"/html/body/div[4]/div[4]/button[2]")
apply_button.click()

In [49]:
#Extracting  the names of vegetables 
for i in range (0,len(final_list)):
    while True:
        try:
            element = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div/div[1]/button')
            element.click()
        except:
            break
    search_input = driver.find_element(By.NAME, 'search_terms')
    search_input.send_keys(final_list[i])
    time.sleep(3)
    search_input.send_keys(Keys.ENTER)
    
    temp = driver.find_element(By.XPATH, '//*[@id="historyDataTable"]')
    time.sleep(3)
    temp_html = temp.get_attribute("innerHTML")
    html_list.append(temp_html)
    time.sleep(3)
    print(final_list[i])

#extracting names of vegetables and prices
Name = []
Prices = []

for i in html_list:
    temp_n = re.findall('<tbody><tr><td>(.*?)</td><td>',i)
    Name.extend(temp_n)
    
    temp_p = re.findall('<td>â‚¹ (.*?)</td>',i)
    Prices.append(temp_p)

#extracting date 
date = re.findall('<th>(.*?)</th>',html_list[0])
dates = []
for i in date:
    temp = re.findall('"white-space: nowrap;">(.*?)</span>',i)
    if len(temp) != 0:
        dates.append(temp)

Onion Big
Onion Small
Tomato
Green Chilli
Beetroot
Potato
Raw Banana (Plantain)
Amaranth Leaves
Amla
Ash gourd
Baby Corn
Banana Flower
Capsicum
Bitter Gourd
Bottle Gourd
Butter Beans
Broad Beans
Cabbage
Carrot
Cauliflower
Cluster beans
Coconut
Colocasia Leaves
Colocasia
Coriander Leaves
Corn
Cucumber
Curry Leaves
Dill Leaves
Drumsticks
Brinjal
Brinjal (Big)
Elephant Yam
Fenugreek Leaves
French Beans
Garlic
Ginger
Onion Green
Green Peas
Ivy Gourd
Lemon (Lime)
Mango Raw
Mint Leaves
Mushroom
Mustard Leaves
Ladies Finger
Pumpkin
Radish
Ridge Gourd
Shallot (Pearl Onion)
Snake Gourd
Sorrel Leaves
Spinach
Sweet Potato

In [50]:
# converting into Dataframe
df = pd.DataFrame(dates,columns = ['Dates'])
df1 = pd.DataFrame(Prices).transpose()
df1.dropna(inplace = True)
df1.columns = [Name]
df = pd.merge(df,df1,left_index=True, right_index=True)

In [51]:
df

,Dates,"(Onion Big,)","(Onion Small,)","(Tomato,)","(Green Chilli,)","(Beetroot,)","(Potato,)","(Raw Banana (Plantain),)","(Amaranth Leaves,)","(Amla,)",...,"(Mustard Leaves,)","(Ladies Finger,)","(Pumpkin,)","(Radish,)","(Ridge Gourd,)","(Shallot (Pearl Onion),)","(Snake Gourd,)","(Sorrel Leaves,)","(Spinach,)","(Sweet Potato,)"
0,2022-08-01,21,38,17,37,43,31,11,10,50,...,17,37,26,30,26,30,30,12,14,38
1,2022-08-02,21,38,17,37,43,31,11,10,50,...,17,37,26,30,26,30,30,12,14,38
2,2022-08-03,21,38,17,37,43,31,11,10,50,...,17,37,26,30,26,30,30,12,14,38
3,2022-08-04,25,38,16,32,45,34,9,10,50,...,13,35,23,26,28,36,30,12,13,37
4,2022-08-05,25,38,16,32,45,34,9,10,50,...,13,35,23,26,28,36,30,12,13,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,2022-12-27,29,39,15,36,35,27,7,13,60,...,16,30,29,24,30,35,30,14,10,38
149,2022-12-28,29,39,15,36,35,27,7,13,60,...,16,30,29,24,30,35,30,14,10,38
150,2022-12-29,27,35,15,36,40,28,10,10,60,...,18,28,25,22,28,29,30,12,12,39
151,2022-12-30,27,35,15,36,40,28,10,10,60,...,18,28,25,22,28,29,30,12,12,39
152,2022-12-31,27,35,15,36,40,28,10,10,60,...,18,28,25,22,28,29,30,12,12,39

In [52]:
# exporting the data into csv file
p='E:\\Masai DA Projects\\AUG_DEC_Prices_DELHI.csv'
df.to_csv(p, index=False)

## Extracting data of delhi from Jan to March

In [13]:
#visiting the page
# homepage = 'https://vegetablemarketprice.com/'
# data = []
# html_list = []
# driver = webdriver.Firefox()
# driver.get(homepage)
# search_input = driver.find_element(by=By.XPATH, value='//*[@id="header-search-input"]')

# #Searching Noida Price History
# header_search_input = 'Delhi Vegetable Market Price History'
# search_input.send_keys(header_search_input)
# search_input.send_keys(Keys.ENTER)
# time.sleep(5)
# driver.find_element(by=By.XPATH,value='/html/body/ul/li[1]/div').click()

#switching from chart to table in dashboard
# switch = driver.find_element(By.XPATH, '//*[@id="navItemTable"]')
# switch.click()

# #selecting the date 
# change_date = driver.find_element(by = By.XPATH,value = '//*[@id="reportrange"]')
# change_date.click()
# custom_range = driver.find_element(By.XPATH, "//*[contains(text(), 'Custom Range')]")
# custom_range.click()

# Initialzing starting date and end date
# while True: 
#     check_month = driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div[1]/table/thead/tr[1]/th[2]")
#     month = check_month.get_attribute("innerHTML")
#     if month == "Jan 2023":
#         break
        
#     else:
#         back_button = driver.find_element(By.XPATH,'/html/body/div[4]/div[2]/div[1]/table/thead/tr[1]/th[1]')

#         back_button.click()
        
# first_date = driver.find_element(By.XPATH, '/html/body/div[4]/div[2]/div[1]/table/tbody/tr[2]/td[1]')
# first_date.click()

# i=0                  #switching page of calendar 
# while i < 1:
#     front_button = driver.find_element(By.XPATH,"/html/body/div[4]/div[3]/div[1]/table/thead/tr[1]/th[3]")
#     front_button.click()
#     i = i+1

# last_date = driver.find_element(By.XPATH,"/html/body/div[4]/div[3]/div[1]/table/tbody/tr[5]/td[6]")  # selecting end date 
# last_date.click()

#applyig the dates 
wait = WebDriverWait(driver, 60)  # Adjust the timeout as needed
apply_button = wait.until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[4]/div[4]/button[2]")))
apply_button.click()

In [17]:
# extracing the names of vegetables
# for i in range (0,len(final_list)):
#     while True:
#         try:
#             element = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div/div[1]/div[4]/div/div[1]/div/div[1]/button')
#             element.click()
#         except:
#             break
#     search_input = driver.find_element(By.NAME, 'search_terms')
#     search_input.send_keys(final_list[i])
#     time.sleep(3)
#     search_input.send_keys(Keys.ENTER)
    
#     temp = driver.find_element(By.XPATH, '//*[@id="historyDataTable"]')
#     time.sleep(3)
#     temp_html = temp.get_attribute("innerHTML")
#     html_list.append(temp_html)
#     time.sleep(3)
#     print(final_list[i])

# extracting the dates from html code
# date = re.findall('<th>(.*?)</th>',html_list[0])
# dates = []
# for i in date:
#     temp = re.findall('"white-space: nowrap;">(.*?)</span>',i)
#     if len(temp) != 0:
#         dates.append(temp)


# # Extracting names and prices of the vegetables 
# Name = []
# Prices = []

# for i in html_list:
#     temp_n = re.findall('<tbody><tr><td>(.*?)</td><td>',i)
#     Name.extend(temp_n)
    
#     temp_p = re.findall('<td>â‚¹ (.*?)</td>',i)
#     Prices.append(temp_p)

In [20]:
df

,Dates,"(Onion Big,)","(Onion Small,)","(Tomato,)","(Green Chilli,)","(Beetroot,)","(Potato,)","(Raw Banana (Plantain),)","(Amaranth Leaves,)","(Amla,)",...,"(Mustard Leaves,)","(Ladies Finger,)","(Pumpkin,)","(Radish,)","(Ridge Gourd,)","(Shallot (Pearl Onion),)","(Snake Gourd,)","(Sorrel Leaves,)","(Spinach,)","(Sweet Potato,)"
0,2023-01-01,27,35,15,36,40,28,10,10,60,...,18,28,25,22,28,29,30,12,12,39
1,2023-01-02,30,35,16,36,34,33,7,13,60,...,18,30,29,24,29,36,28,15,11,39
2,2023-01-03,30,35,16,36,34,33,7,13,60,...,18,30,29,24,29,36,28,15,11,39
3,2023-01-04,24,38,17,37,31,32,7,11,70,...,14,32,24,27,28,32,31,13,11,37
4,2023-01-05,24,38,17,37,31,32,7,11,70,...,14,32,24,27,28,32,31,13,11,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2023-03-27,19,49,24,38,30,32,7,12,50,...,18,41,20,25,27,31,27,13,11,36
86,2023-03-28,19,49,24,38,30,32,7,12,50,...,18,41,20,25,27,31,27,13,11,36
87,2023-03-29,22,56,21,38,29,28,10,15,60,...,16,50,24,21,27,32,29,13,13,37
88,2023-03-30,22,56,21,38,29,28,10,15,60,...,16,50,24,21,27,32,29,13,13,37
89,2023-03-31,22,56,21,38,29,28,10,15,60,...,16,50,24,21,27,32,29,13,13,37

In [19]:
df = pd.DataFrame(dates,columns = ['Dates'])
df1 = pd.DataFrame(Prices).transpose()
df1.dropna(inplace = True)
df1.columns = [Name]
df = pd.merge(df,df1,left_index=True, right_index=True)

# exporting csv file 
path = 'E:\\Masai DA Projects\\JAN_MARCH_Prices_Delhi.csv'
df.to_csv(path, index=False)

In [21]:
for i in final_list:
    if i not in Name:
        print(i)